### ISSUE TITLE
Adding CSS is awkward

### ISSUE THREAD

**Issue by alexwarren** [textadventures/squiffy#36]
You have to modify style.template.css - would be better to have a way of just extending it, so you can add to the default CSS instead of replace it.

**Comment by alexwarren** [comment]
Actually it's easy enough - you can include a style tag in your output. For lots of UI customisation you should use the `--scriptonly` option and create your own UI.

**Comment by pzolla** [comment]
Could you provide a bit more explanation?  Do you add this option when installing Squiffy with Node or when running Squiffy file?  Is this documented somewhere?

**Comment by alexwarren** [comment]
I haven't documented this anywhere yet as it's new. The index.template.html has been changed so that it calls Squiffy using a jQuery plugin. This means you make any element on your HTML page a "Squiffy" element where the game will appear.

So if you want a heavily customised UI, create your HTML as if it was just a normal stand-alone web page. If you want the game to appear in a div element called "squiffy", and you have a restart button called "restart", you can initialise it using this JavaScript:

```
$('#squiffy').squiffy({
    restart: '#restart'
});
```

Now when you call Squiffy from a command line, you don't need it to generate the HTML or CSS files for you. You can call

    squiffy mygame.squiffy --scriptonly

and that will create just the `story.js` file, which you can include in your own HTML.

**Comment by pzolla** [comment]
I am not finding these to be the equivalent, should they? 

Using the following format that is based on the code generated by the compiler does initialize the restart link.
```
$(function(){
    $('#squiffy-output').squiffy();
    $('#squiffy-restart').click(function () {
        $('#squiffy-output').squiffy('restart');
    });
});
```
However, using the format you note above does not.
```
$('#squiffy-output').squiffy({
    restart: '#squiffy-restart'
});
```

**Comment by alexwarren** [comment]
Correct, things are a bit changeable at the moment - that second version
won't work now! When in doubt, do it the way the generated HTML does it -
hopefully that should be stable now though, I'm not expecting to change it
again.
