### ISSUE TITLE
Labels should be scoped to the current output

### ISSUE THREAD

**Issue by alexwarren** [textadventures/squiffy#40]
When replacing text, if there are multiple Squiffy output divs on a page, the replacement shouldn't apply to all of them.

See http://docs.textadventures.co.uk/squiffy/replace.html

**Comment by caberg** [comment]
well if you decide to replace in whole game, not just current section.

then there's no something wrong in http://docs.textadventures.co.uk/squiffy/replace.html because all of them have same exact label 
```
I walked to the shops and I bought {label:1=a pint of milk}.

Or maybe [I bought something different?](@replace 1=a loaf of bread)
```

```
I walked to the shops and I bought {label:1=a pint of milk}.

Or maybe [I bought something different?](next passage)

[next passage]:
@replace 1=a bottle of whisky

```

```
I walked to the shops and I {label:1=bought a pint of milk}.

But I was [thinking](@replace 1=thoughts)...
```

it's just natural each action will replace all of them

**Comment by alexwarren** [comment]
Yes but you can have multiple games on the same HTML page, then there will be a clash of labels. It's not a common occurrence, but it's exactly what we use on the documentation pages.

This should be fixed now with my latest change, I just need to regenerate the documentation using the latest version.

**Comment by caberg** [comment]
ahh i get it now, sorry for my misunderstanding
