### ISSUE TITLE
error: cannot find module 'underscore'

### ISSUE THREAD

**Issue by caberg** [textadventures/squiffy#47]
recently just delete  fork and fork squiffy again because of troublesome updating with textadventures/squiffy because i'm new with this github

then delete my local repo (which i think it's easy than using crap command in git console) and clone again from my remote repo (using git console ofcourse) in same folder as before which is c:/projects/squiffy , and im happy because now i have fresh copy of squiffy then i compile my test file but i got this

![22222](https://cloud.githubusercontent.com/assets/2444037/6886473/782c29e2-d66a-11e4-8ff3-cfe799019a82.jpg)

is this mistake on my side ?

**Comment by alexwarren** [comment]
Type "npm install" to make sure all packages are installed.

**Comment by caberg** [comment]
great thx now it's works
