### ISSUE TITLE
Non-ASCII passage names

### ISSUE THREAD

**Issue by Oreolek** [textadventures/squiffy#52]
Would be nice to allow passages named in Unicode, not ASCII only.

**Comment by alexwarren** [comment]
In theory this should already work properly, but something is making it not work all the time.

I just created this quick example http://docs.textadventures.co.uk/squiffy/scratchpad/?gistid=c5ddaf96e71ad6d7180d&filename=unicode.squiffy

The Unicode "shrug" and Chinese characters don't work. The emoji does though. I'll see if I can work out what's happening. If you have other examples please let me know.

**Comment by alexwarren** [comment]
Actually the Chinese characters *do* work - I just mis-pasted the section header in the example. And the shrug example behaves strangely because of the backslash character, so I'll fix that.

So it looks like generally Unicode characters work properly, so please let me know which ones don't!

**Comment by Oreolek** [comment]
Sorry, looks like I just mispasted my code too.
