### ISSUE TITLE
Squiffy would not fully load in Windows 7

### ISSUE THREAD

**Issue by JohnBlood** [textadventures/squiffy#58]
Last night I went to work on my IF with Squiffy, I clicked the icon and went to check my emails, Then, I realized that Squiffy had not started. I clicked the icon a couple more times, but noting happened. I figured that the install had become corrupted for I redownloaded the file and tried to reinstalled, but it failed becaise it said the process was inuse. I looked in Task Manger and there were at least 10 instatnces of squiffy,exe running with less than 1,000k of ram each. I couldn't kill them from the TM, so I restarted and reinstall Squiffy, It runs fine now. Just kinda odd.

**Comment by alexwarren** [comment]
Thanks for the report, but nothing I can do without being able to reproduce the issue.
