### ISSUE TITLE
Ability to create external hyperlinks

### ISSUE THREAD

**Issue by levicki** [textadventures/squiffy#59]
Currently creating a link such as `[[link]](http://levicki.net/)` does not produce desired effect (link just becomes disabled after clicking). It would be nice if possible to open the link in new tab/window.

**Comment by alexwarren** [comment]
The syntax for external links is the same as Markdown, so single braces:

    See [this site](http://textadventures.co.uk)

**Comment by levicki** [comment]
Thanks for clarifying, as a newcomer to markdown I wasn't aware of that, and it is not documented in Squiffy help (or at least I didn't find it).
