### ISSUE TITLE
Windows Vista compatibility

### ISSUE THREAD

**Issue by levicki** [textadventures/squiffy#60]
This is more a question than an issue or feature request.

Is there a specific reason why Windows Vista is not supported?

If you manually unpack setup and run the application executable it fails to load due to the reference to Shell_NotifyIconGetRect() function from Shell32.dll. On Windows 8.1 I don't even see the application using any notification icons so unless there are other compatibility issues I fail to see a reason why it wouldn't work.

**Comment by alexwarren** [comment]
Squiffy is built using Electron which does not and will not support Vista, unfortunately https://github.com/atom/libchromiumcontent/issues/66

**Comment by levicki** [comment]
So a false dependency on an Electron feature which your own code does not even use is blocking the use of your program on Vista. Interesting...
