### ISSUE TITLE
Links at http://docs.textadventures.co.uk/squiffy/ point to older version of Squiffy

### ISSUE THREAD

**Issue by alice-blue** [textadventures/squiffy#66]
The links in "Or you can download Squiffy for Windows, OSX or Linux" point to Squiffy 4.0.

Reported here: http://forum.textadventures.co.uk/viewtopic.php?f=24&t=6270#p42514

**Comment by alexwarren** [comment]
Thanks for reporting this, I've update them to point to the Releases page on GitHub now so I won't need to remember to update them for each release!
