### ISSUE TITLE
Comparison operator issues

### ISSUE THREAD

**Issue by alice-blue** [textadventures/squiffy#68]
The result of this code:

```
[[Begin]]:

@set N = 8

N is {N}.

A) N<9 is {if N<9:true}{else:false}.

B) N<9 is {if N<9:[[true]]}{else:false}.

C) N < 9 is {if N < 9:true}{else:false}.

D) N < 9 is {if N < 9:[[true]]}{else:false}.

E) N < 9 is {if N < 9:[[TRUE]](true)}{else:false}.


[[true]]:

This passage does not display even if you click "true" in D and E.
```

is this:

> N is 8.
> 
> A) N<9 is true.
> 
> B) N<9 is false.
> 
> C) N < 9 is true.
> 
> D) N < 9 is true.
> 
> E) N < 9 is TRUE.

B says "false" when the intended result is a linked "true," and D and E both get links, but if you click them, nothing happens.

Another weird thing is that < sometimes behaves differently than <= or >= or >. In the following code, the <= and >= and > all seem to  work as intended, but the < does not. Even if you decrease the score repeatedly, you never get to see the link that takes you to the "Low" section.

```
@start first


[[first]]:
@set x = 6

[[Begin.]](MainPassage)



[[MainPassage]]:

Your score is {x}.

[[Increase score by 2.]](IncreaseScore)

[[Decrease score by 2.]](DecreaseScore)

{if x<4:[[Go somewhere else.]](Low)}

{if x>=4:{if x<=10:[[Go somewhere else.]](Medium) }}

{if x>10:[[Go somewhere else.]](High)}



[[IncreaseScore]]:
@inc x 2

Your score has increased by 2.

[[Go back.]](MainPassage)



[[DecreaseScore]]:
@dec x 2

Your score has decreased by 2.

[[Go back.]](MainPassage)



[[Low]]:

Since your score is under 4, you are in the Low Score Zone.

[[Go back.]](MainPassage)



[[Medium]]:

Since your score is from 4-10, you are in the Medium Score Zone.

[[Go back.]](MainPassage)



[[High]]:

Since your score is over 10, you are in the High Score Zone.

[[Go back.]](MainPassage)
```

More discussion and examples here: http://forum.textadventures.co.uk/viewtopic.php?f=24&p=42875#p42873

**Comment by papadasoft** [comment]
Boths issues are solved and the updated in master / Ambos errores se han solucionado y han quedado actualizados en la rama master
