### ISSUE TITLE
0-byte jquery.min.js

### ISSUE THREAD

**Issue by keiyakins** [textadventures/squiffy#72]
Currently, when built on Windows 7 (32-bit) using the GUI, the output jquery.min.js is zero bytes. Understandably, the generated code that relies on jquery then fails immediately.

Possible solutions, in order from best to worst:

- Stop relying on jquery (if you want to keep the zero-byte file for sentimental reasons, you can always use [vanilla js](http://vanilla-js.com))
- Put a proper copy of jquery in the output folder
- change to use a url on the web - utterly breaking offline use in the process.

**Comment by alice-blue** [comment]
I'm belatedly realizing that this is probably the same issue I'm dealing with, reported as #74.

"Build" worked correctly in version 5.0 of Squiffy, so something presumably broke between versions. I wish I knew a workaround better than fixing the jquery.min.js each time you build.

**Comment by papadasoft** [comment]
New minor version is released. Can you try if solved this error?
