### ISSUE TITLE
"Build" results in a web page that is blank except for the "Restart" link.  jquery.min.js file is blank.

### ISSUE THREAD

**Issue by alice-blue** [textadventures/squiffy#74]
With the latest downloaded version of Squiffy, building a project and then opening index.html in a browser results in a page that is blank (except for the "Restart" link).

The console says:
```
Uncaught ReferenceError: jQuery is not defined
    at story.js:611
    at story.js:622
    at story.js:637
index.html:18 Uncaught ReferenceError: jQuery is not defined
    at index.html:18
```

To reproduce:
In the latest downloaded version of Squiffy, create a new project that is empty except for the word "Hello."
Click "Build".
Open the resulting index.html file in a browser.

This worked correctly with version 5.0 of Squiffy.

**Comment by alice-blue** [comment]
When I "build," the automatically-generated jquery.min.js file is blank. Copying the contents of the jquery.min.js file from the Squiffy folder into the blank file seems to correct the problem. But the next time I "build," the the automatically-generated jquery.min.js file is blank again.

**Comment by papadasoft** [comment]
I new versión is released for fix this issue, Can you try it?

**Comment by alice-blue** [comment]
I installed version 5.1.1, and it works now! Thank you!
