### ISSUE TITLE
"Run" and "Preview" both broken in Squiffy online editor

### ISSUE THREAD

**Issue by jeremydouglass** [textadventures/squiffy#87]
After loading the Squiffy editor at https://textadventures.co.uk/squiffy/editor

* Pressing "Run" switches to the Output tab, which remains empty (even with the default starter template text).
* Pressing "Preview" forwards to https://textadventures.co.uk/squiffy/preview and displays the error:

> Sorry, something went wrong
> An error occurred while processing your request.
> 
> This has been logged, but it would be really helpful if you could let us know a bit more information about what you were doing - please [contact us](https://textadventures.co.uk/help/contact) and we'll do our best to fix things.

Related forum discussions:

* https://textadventures.co.uk/forum/squiffy/topic/uq3h1qqgw0g9to0o_7i4cw/i-cant-preview-my-game
* https://textadventures.co.uk/forum/squiffy/topic/fiz15pek0ka0qqgnl3b6da/i-cannot-preview-or-run

**Comment by behr201** [comment]
8 months later, same here

**Comment by PrestoGuys** [comment]
Over 2 YEARS later, Still Broken. :( :( :(

**Comment by alexwarren** [comment]
This has finally been fixed! See https://textadventures.co.uk/forum/squiffy/topic/zefgfs4lqkq3arknwjhqkg/various-squiffy-issues-are-now-fixed
